CREATE TABLE admins (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,

    full_name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,

    -- optional extra fields
    phone VARCHAR(20),
    role VARCHAR(50) DEFAULT 'ADMIN',

    -- status: ACTIVE, INACTIVE, BANNED
    status VARCHAR(20) DEFAULT 'ACTIVE',

    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
